FROM python:3.9-slim

RUN groupadd user && useradd --create-home --home-dir /home/user -g user user
WORKDIR /home/user

# Upgrade pip with no cache
RUN pip install --no-cache-dir -U pip

# Copy every file in the source folder to the created working directory
COPY  . .

# Copy application requirements file to the created working directory
COPY requirements.txt .

# Install application dependencies from the requirements file
RUN pip install -r requirements.txt

USER user
#RUN chmod +x ./start.sh
CMD ./start.sh