module.exports = {
    contributionRequest: require('./contributionRequestModel'),
    contributionFilter: require('./contributionFilterModel'),
    paymentGateway: require('./paymentGatewayModel'),
    paymentPaypalPlan: require('./paymentPaypalPlanModel'),
    paymentFilter: require('./paymentsFilterModel'),
    payuCreatePlan: require('./payuCretePlanModel'),
    payuWebCheckout: require('./payuWebCheckoutModel'),
    mercadoPagoCreatePlan: require('./mercadoPagoCreatePlanModel'),
    serfinsaCreatePlan: require('./serfinsaCreatePlanModel'),
    reportsDonation: require('./reportsDonationModel'),
    reportsUsersByPackage: require('./reportsUsersByPackageModel'),
    reportsUserUnsuscribed: require('./reportsUserUnsuscribedModel'),
    reportsPaymentsByPackage: require('./reportsPaymentsByPackageModel'),
    subscription: require('./subscriptionRequestModel'),
    subscriptionFind: require('./subscriptionFindModel'),
    userSignIn: require('./userSignInModel'),
    userBindUser: require('./userBindUserModel'),
    userLogin: require('./userLogInModel'),
    userDelete: require('./userDeleteModel'),
    userChangePassword: require('./userChangePasswordModel'),
    userUpdateProfile: require('./userUpdateProfileModel'),
    userGetRegisterUsers: require('./usersGetUsersModel')
}